{{- if .Values.embeddings.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: bge-embeddings
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    app: bge-embeddings
    {{- include "opengatellm-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.embeddings.service.type }}
  ports:
    - port: {{ .Values.embeddings.service.port }}
      targetPort: {{ .Values.embeddings.service.targetPort }}
      protocol: TCP
  selector:
    app: bge-embeddings
{{- end }}