{{- if .Values.whisperx.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisperx-models
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    {{- include "opengatellm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: whisperx
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.whisperx.persistence.size }}
  storageClassName: {{ .Values.whisperx.persistence.storageClassName }}
  volumeMode: Filesystem
{{- end }}