creation_rules:
  - key_groups:
      - age:
          - age15fyxdwmg5mvldtqqus87xspuws2u0cpvwheehrtvkexj4tnsqqysw6re2x #Jacques Roussel
          - age1qy04neuzwpasmvljqrcvhwnf0kz5cpyteze38c8avp0czewskasszv9pyw # ArgoCD Hors-Prod
          - age1zh33t0mqh3mpsvclhtp6rfvlru3aa4jy6du0ud79jhn72kz9j40q5vnkat # Alessandro Mosca