apiVersion: v1
kind: Service
metadata:
  name: albert-api
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    {{- include "albert-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: albert-api
spec:
  selector:
    app: albert-api
  ports:
    - port: {{ .Values.albertApi.service.port }}
      targetPort: {{ .Values.albertApi.service.targetPort }}
      name: http
  type: {{ .Values.albertApi.service.type }}
