apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  postgres_entrypoint.sh: |
    #!/bin/bash
    set -e
    
    echo "Creating additional databases..."
    for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
      echo "Creating database: $db"
      psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER -d $POSTGRES_DB <<-EOSQL
        CREATE DATABASE $db;
    EOSQL
      echo "Database $db created successfully"
    done