apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: default
spec:
  selector:
    app: qdrant
  ports:
    - name: grpc
      port: {{ .Values.qdrant.service.grpcPort }}
      targetPort: {{ .Values.qdrant.service.grpcPort }}
    - name: http
      port: {{ .Values.qdrant.service.httpPort }}
      targetPort: {{ .Values.qdrant.service.httpPort }}
  type: {{ .Values.qdrant.service.type }}