apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vllm.service.name }}
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    {{- include "albert-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: vllm
spec:
  ports:
  - name: http-{{ .Values.vllm.service.name }}
    port: {{ .Values.vllm.service.port }}
    protocol: TCP
    targetPort: {{ .Values.vllm.service.targetPort }}
  selector:
    app: vllm
  sessionAffinity: None
  type: {{ .Values.vllm.service.type }}