apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    {{- include "albert-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: vllm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vllm.persistence.size }}
  storageClassName: {{ .Values.vllm.persistence.storageClassName }}
  volumeMode: Filesystem