huggingface:
    token: ENC[AES256_GCM,data:CtXzYPtJZMRryZjfTP1DoXuNjJPYwzObHbKyRakPQu4jB42+Hw==,iv:mmBsW44nuRxXY16G7HSXnfeU6W8/b7HGnqg+VWGFIV0=,tag:JnjAwg/log/oCeSLMojg9w==,type:str]
albertApi:
    config:
        models:
            - id: ENC[AES256_GCM,data:QvqeRz8HbGIjNjEA,iv:j6Mim+gC0YvwEwoUmeHAPFJ7yCVXNZQhTxA3z8U0CJI=,tag:n3erMz7gcDN1khL9a+U/NA==,type:str]
              type: ENC[AES256_GCM,data:GqDf0j6JJobb4Ry1eLFS,iv:g5bqIkDPs+Ak/OsFY7jdt+CEiihhNzzJ5NzoukPsic4=,tag:Tr839GY9CX7DCQ42RK6NqA==,type:str]
              owned_by: ENC[AES256_GCM,data:vJpEZd7lsR0F7Zxj4p+HNgE=,iv:sGFyZFMmeC5HdX90DfnqFIy8CfVq8gtQfymd64X7cZc=,tag:B3mV2LYECStjPyuYIhCuNQ==,type:str]
              clients:
                - model: ENC[AES256_GCM,data:RjbJiTVzHyDu/0/E,iv:c+YM4s49K+UJ1g4m5+UxR86Io5ePQG448+Nugi+7qRw=,tag:HDXRqP9ja6/LsraBI+z2KA==,type:str]
                  type: ENC[AES256_GCM,data:M3WCo9ta,iv:gko8sRvyd/UQ7H2wTgWdIabMmuAO3aj9KKLwEJarigc=,tag:VNZWwTFTu0HqYWw4yBYscQ==,type:str]
                  args: null
                  api_url: ENC[AES256_GCM,data:mdpnTeQ4qoGp/Hjq3jics75yumHVmWv6UmggmJF/yR5S,iv:7X9/fkq44TTHYjNG+gQr2Lxg6CSxfoBliVNxRjfpth4=,tag:4Bk7Sw0SGYMmKiY47SImdg==,type:str]
                  api_key: ENC[AES256_GCM,data:JX/QVEkkqcHaSSXDc7UXmcOyxWq7bR9Mzjn4helzxcsrYdDI8hDnTJGs6RxowjroeO3veH25yNipEjCY4ZgtsYr3Lf5s/BpJ6alykqLLdIxQu48v4kQKhKW9EjJkDjMm3RYyHlHcy3Fd+hn7d67SS8pTQtDj0eGc+za9j6J0T7Hx6Lny/XkdKWxVJX69nLxWzsATG5LSwwLTJilz0ZE=,iv:e7/yJBPPb7tg+xjXPL2fms6BpOJhIKftrZFjKoIfEX4=,tag:p4CWGUEjyhcsqsLbekUvkg==,type:str]
sops:
    age:
        - recipient: age15fyxdwmg5mvldtqqus87xspuws2u0cpvwheehrtvkexj4tnsqqysw6re2x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbE02eWN3WU5BUmhhU0Nr
            c1FKeWRvZXlNcy95cXBGVUd0aXFaTWVDK1h3CkFiaW1URUEvZVRmbCtXeXh5ZXZv
            MGowZkh2emF1bnNKcnJMNnFuU1FjUzAKLS0tIEs3SFBsMG5POFNtQ0tSbWFvcjVF
            YnZkRjFiTEFNWlZhc3YzTjdrdFdtR1kKi3tUPR2WKfg8ZJrMY9ZKRb7BXU9j/5MK
            Y3xiAmh8/IJlGkWr4NIHtRmvCUQNMqBYSJnAjBTu+3fRdNELqW/N7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qy04neuzwpasmvljqrcvhwnf0kz5cpyteze38c8avp0czewskasszv9pyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbTdGQ0VMc0xoLytta0Zo
            L2t0WDd0SktXRHJXcnllejBQZzBtTi9wQ0FJCmhWTVMzeDdmVTlxbi8yRTl6d1cr
            dW5YN2RCOTcwM216eEMyN080azlMR3MKLS0tIDlUL0lpSlV5YllLQUJHZUcvUzVB
            UkJkT2lTZWFDTkJHM0lyN2RjUEczTmsKy9D6/1cKAqi0s9NPvHDPDNbiM+9WkcGL
            ujoHuDvckf1JFux/6gXnMz1qfhJj18G7kay2rd1Q8i4AvQFRNWv3vA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zh33t0mqh3mpsvclhtp6rfvlru3aa4jy6du0ud79jhn72kz9j40q5vnkat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaFo3eHMrTHRLK0M3R00x
            UFF1ZldXTlVGOUlWK2FQRDk2WVVxNFkxaURrCnpPVnB6bjVDZUx4dERUTThEUGUz
            T1ZKNG4wenVHL0VkNTlwQ3czelh3QTAKLS0tIGFJUWczSkgyVlZVbnRiWVlhMkRC
            c3BZT0k4eEc3VzJxRXdYQ25kQ1dQNVkKY0h0DHZS5q2kndRhS42MZgsszZxj8Qxo
            ub2wjOtdwzDNhpPD3aBpIImjA4qgSk/WLi/WTXd/6fNwpKRzds6TAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xvckqrat9q6lfh24ax6y65qzde6krm4a2s0uc83ursr7gas8eavswf5kpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYkgwZWFGOHBrMjNvdnpW
            Q1p4aG5SSE84TUNINWlwZ05wc0hPUUw1YWtJCmpOTFUyR1JFbkRORmtQYjlqNWFj
            SGFXVnZ3UXFSZE5KMG9BOENlUVhuMXcKLS0tIDdnWTZBSWdXbC9TZGFRVVFieTlZ
            bERqMWpPVE1SRjJBdWpCd01JclpQQ00KGfeArXypv62XjToWOh0baa3Z6MkoQmZu
            2EkuSXjP+XRv+aE+C+FyYqaG1sWb9m6xsQiGmltali93dCu6AWiH6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-24T12:39:52Z"
    mac: ENC[AES256_GCM,data:mXHL13ZQi+TbTnhKDLfph/cnf6Ety+N0DSXnAwCckK0uuCIc/xvlfs/rgW5+mTFGt93caylso1/hYTBHa1TD52ZQPSiQkpOj+ksn/pcklMBUWuJLtjrH2KfPuyQ5fhUuT0I+uJNN0OR1tRXSRPYmrJUSwxmKSfbDOc96VOG50GQ=,iv:G9+zmBlJE/uZ/UMSzV3Q0IiI0DRkz/sSTxwGiKoJ60A=,tag:y3bl3gkGDdu3PUsthmFleg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
