global:
    redis:
        password: ENC[AES256_GCM,data:JpBwhZcIDr0=,iv:wdkbQkpnUsTvTEhpA8aSGbLGqUBcRcsv1YstYq408JE=,tag:S/qF87ZLRNGVjCl0c3nTAA==,type:str]
albertApi:
    config:
        playground:
            api_url: ENC[AES256_GCM,data:Ul20sfRFWP4xBJl09qnoEDGvp0RJCeousvD+Gjq5ahDHECViMEuSLpGCRWKi,iv:U3Fm726abuXCWTKK6V3lCG28anYB0E33vV0d4xQ9w7I=,tag:J1pW2ylExy6R+nVjTKo91Q==,type:str]
            postgres:
                url: ENC[AES256_GCM,data:XBUUkMeuovnzqJkmy0T4V/rha9hwqYVV1tEVRLh6Vv9pHEaERSEQrrZxIMTqRqyHcDHYF9vNMybEscqnb5QKnGyK9dvkxoQ1O0ZAqF2e9X8Pe4uD2TewMzi/GTK+bEXp9acfjBYkrpv6Ura5JwxpPJ/M3QC073fv0wX+0byf0m7o11H+ImdFNGqkF/t4DiFSt2pKG9Uvde1eeWC7Tg==,iv:BtkBrmSWZYD+xUBgx8RtdL8rsoXbyx4ZdmLV6BggIQA=,tag:6REkckCqtLW9n4zFLO2wFQ==,type:str]
        settings:
            auth_master_username: ENC[AES256_GCM,data:4l5A8HhB,iv:9b//i2VgGGraT8vOlSN/5Q4Mf8rEMVMZShLOVSpJiek=,tag:HSvF9lvNxnGwAzKRAcRIvw==,type:str]
            auth_master_key: ENC[AES256_GCM,data:cl+C4jOIL2E=,iv:YFr1j8l84V3rpHVyPJPe17UJzn8FpBQCdeDKRobY1TQ=,tag:duz4jkAsdUGIIJVe/MHPHQ==,type:str]
            #ENC[AES256_GCM,data:64hrfbvVTzvNWLdJ10XrIn4WUW46OYpo+9vUNUSeEFpgbswvMHWrLAnVFL3HuOGr,iv:t0bmnBw0LMQnr63mNfIRpUUKhtY21pIMOnX1gXPwiW8=,tag:kdRVm/LZp5jjuGJr36xVPw==,type:comment]
        dependencies:
            postgres:
                url: ENC[AES256_GCM,data:qntP4rMxxMrr6RSw/KdLb55zAij2GTH0uDVGoWXCe2p1JHlWrllcIYsRFlWllFYrxExNpUiFkXQE4Wo3CMVIr8ognF4wCSJxewuUoEeGm+qlUemxfje6jFmC6uTXF7x8OM8s8iH/xGBDQLAcLu9k2BJtMYoe/DMqj3725ouzNI4/IveqvS8GHTd8VsmJdILFG6Cn8JgsLwElt532CDo=,iv:lRstHaqAQucIemr0y85M8XMF36XgLbKCs3ZK195b7KY=,tag:mu1jd6IoxYbV31YpFH9qnQ==,type:str]
                echo: ENC[AES256_GCM,data:tbFZdgw=,iv:zlK98W7h+CQREdBYNmYwBRd9t0xMOcC1i8UEZlcLxSY=,tag:GNzNo7/BfkFnKYPW8KXlww==,type:bool]
                pool_size: ENC[AES256_GCM,data:Bg==,iv:cOBMA/O+HeLrg09loG1ssdD5rUojFSlDC+URR7KHBPM=,tag:0lCvy9DdzJ/mEIfxUGmLxg==,type:int]
                #ENC[AES256_GCM,data:bw2uS/5tex+ZIbFtT8EpcLZjyQ==,iv:HVJ2tQL120rhGZ9EFdr38+VvUOhEVzPvNYCZPLBhdH0=,tag:As0m7b5GcFHjbnD2ikIoDg==,type:comment]
                #ENC[AES256_GCM,data:Iae071Uvz59sV1xSp8zLZq0DPZml4q/nvJNrHgz4YNizs8otuO+dS0GUV48dca1pnQVYa/u+//KbDwbvLkVCvhx8Lbmnd+QW8ti4,iv:5ImfOEpeb4g21k7U4aEWR1oyTgNntQbPPPrqchAyy64=,tag:0A3wlyCSwq1/rTLC63UU2g==,type:comment]
                #ENC[AES256_GCM,data:ZJKrz2Dzhb7dCNqGmPIwGPtY7nAAciu1CojV/Bf2QRxQ,iv:04yhBsVs9k92HXmb9LMfhyIYg8XNV4GBdELTFGefbBQ=,tag:udMzr2ABkHCM4HytHmUalQ==,type:comment]
            redis:
                host: ENC[AES256_GCM,data:BhgI4X/9Fkl0nI7F0IKs6IJre9Q7HHPfh+tK1IBdfZUS6bGGnBTZVV0=,iv:nBYdV6fZbRvau2I8fmPjXVp7zCSSZBFiJpnyIHMbuSI=,tag:lzzmHz5ttdlL9WaJE5m0CA==,type:str]
                port: ENC[AES256_GCM,data:oALDwg==,iv:+MSZ4zTOeOng+IXuuNQZlpIspyDVXFqWyU5kJTD3aZU=,tag:B9n2JGVlxNZp/kGY4Tfn9A==,type:int]
                password: ENC[AES256_GCM,data:NDKz7FsU1ss=,iv:wHg933Y5lP9OZrqqMLuxOWMGGhXxQQQqbhnuf5JbTQo=,tag:blwgYWriyCzqdQAbIQ1ayA==,type:str]
        models:
            - name: ENC[AES256_GCM,data:CxounXkBtwAZvWY=,iv:iOA+AaKTRsNOINEVY0Eo44niL/TrhdeNfEMGkGLEpK8=,tag:mCXU2PdQZXkTgY3PoHKF+Q==,type:str]
              type: ENC[AES256_GCM,data:GqDf0j6JJobb4Ry1eLFS,iv:g5bqIkDPs+Ak/OsFY7jdt+CEiihhNzzJ5NzoukPsic4=,tag:Tr839GY9CX7DCQ42RK6NqA==,type:str]
              aliases:
                - ENC[AES256_GCM,data:TE+vbIddb5JUH2FryPMV2a8F/AeuAZFI2k6zJMA=,iv:pt4efnVqdV37FAfm4m39C/UOqRhAVmTCsxNlBbQ5uEc=,tag:QEYrS8l5RXrQ0UWsWFxIkg==,type:str]
              owned_by: ENC[AES256_GCM,data:9PhLokCFYBxBN7oGtm+eLw==,iv:MhKkFN5p/xKQeXtZQygUQgO9d6B85Ghyjgw6hkcV2s0=,tag:lVMInWWwXz5n+ycP/N2/zA==,type:str]
              providers:
                - type: ENC[AES256_GCM,data:/6NxEA==,iv:05aCl8KPrDl2oUdV+oVbt+EuGuQAI/ppGoJd9lg85sY=,tag:rTxEnEJR7dvbr09KPS0IbQ==,type:str]
                  url: ENC[AES256_GCM,data:yv2xAEaiojkr4Yo7M4nv0f7Z0yHuumWtlQdycMhadIjq+g0hyFv3KuB1oehtD4c1,iv:YCbAgBl0elEdvIcdj5lcv2Fdy4FMa68q8Oq6ojwgCck=,tag:4MZsWGmopiTyDt1gLhNvfg==,type:str]
                  model_name: ENC[AES256_GCM,data:+WLSxRg3ALcgw896EyFFYJV2VVskNNshequDEVM=,iv:PGABdVsL7muY1cii3Gm0WW1aUX8rIARlPTSFoel74Bk=,tag:TCBDWEgZcwvJNTE96Y8+Cw==,type:str]
                  key: ENC[AES256_GCM,data:d0njltPnAsjsOGXZ53yhQgRtJmAP3i8bMkiHMrjRAkD+xYGLzZjrf1egPPBKdEp9txG6BWGw7ufnxVjmdOSAgw==,iv:tyV8CqvlRZTc/+nAB7o4opYG6KiuTovPodSCBb6/JOM=,tag:kTCj/ZJ1j3wcmAsGGfhHyw==,type:str]
                  model_carbon_footprint_total_params: ENC[AES256_GCM,data:O/o=,iv:WFt9k5DDR46O5Pzbu/kZFjPORCXvjS1j9wiF/80MA2s=,tag:zHC+4MGyn+6qBqanSjhFbA==,type:int]
                  model_carbon_footprint_active_params: ENC[AES256_GCM,data:k50=,iv:k7Thgccsdt5EuEIvxJOXzBUL8uH7n5FURdg5V3jCliE=,tag:fKV5oItrJrhh9rzgySd9yA==,type:int]
                  model_carbon_footprint_zone: ENC[AES256_GCM,data:iDA9,iv:7gTNhcXBgyKe1DA/Asup0Mil/0EHNGpPl+Vx9hedeKU=,tag:eXdQBC6hLfO7POjtbJeivw==,type:str]
#ENC[AES256_GCM,data:ab1XcCg6hSxKYkWCN0PwEu39PweF6Wlkz7OvL41t3cc=,iv:VDTz0JwF5siHTIEtpZNw0FdB11ShBMRDx+sit94jhq0=,tag:4XtErEGXnLeggwPO9DNp9g==,type:comment]
#ENC[AES256_GCM,data:jAvJgL+c84nEaPIw5KPVTGf8BgU1GCKQNbNUzG6Xa4kuLBk=,iv:itsCr1SDqdSm/odIGrH+ZTr/KYET32L3jx60YwepV5M=,tag:wFMIcWw1fm/PU0hoOrs7cg==,type:comment]
#ENC[AES256_GCM,data:nFHp4Cx6Fu7nFT6npX5blcW5ZtDO/MBUxNBksiVq+wLEMU8XnbZLWjo=,iv:iChLFNi3hT0ciGXbupYsb8VSCXDFEDFJ0T4X7+YeDjY=,tag:lgxX4+jwACImcOJiHmk1KQ==,type:comment]
#ENC[AES256_GCM,data:oolK2OqYmUv8B8OjkzAq/CAuzjgkaLmf,iv:hAygi74q32UV5P75UZKc2E0hvmFOdM4lfvs253tFLc0=,tag:ylJmCrGIAgkco66fvyn3Tg==,type:comment]
#ENC[AES256_GCM,data:0j5bAttgM01XsKALnVeL4RKo715G2TVR7oHaUC3qhAhJlF2Kb/pcxr73,iv:LG93OqjR01yImleK8M6tPTWG54+PR0YKwJur+u1dqLw=,tag:KrYSsggVfizzLnnERH5ikw==,type:comment]
#ENC[AES256_GCM,data:qN0JI8jWsrhD6rotWzQuJ0z16ef9//28osFu5CRF,iv:fpZUSm4zIRYU4R8wO/YiDJ7PJsglEcQq4udKwFywWsc=,tag:7PlOCZGkzVmmh/qnjothhw==,type:comment]
#ENC[AES256_GCM,data:QlI4DSA3eSrcbZxVcXBolxYOTM/cU8EgpRkFyq1iwt7XG29i3dr6qe79xISzAZyMKCBBO90tb1xlYCMLThaInA==,iv:kjiKw8t+/tY8AweC2/SUaH6ii9Ex+Ip5j+LYwlSQ8eU=,tag:zScBYPArXge4DOpZNRsorQ==,type:comment]
#ENC[AES256_GCM,data:7oClvyd2B1e3dJGWF4/3sENM3m5LIw1kpN7XJqCduRd49Nu7vDgZ7wqby98TGiHjcecu7xBYbg4UZA3VNmNYQr3Mp32mvK/7BzDZYwgFrnI1Kf8B7a0/1qxjIkBQXOSWZl23RPAs+szMsU1sQuJv7uroXxZ7+q0gTjZHcqceP3QENIeRq5IGFfZ+76b2fnLVfo8+fhM9ZNZ40MTtDy3oP1EHVn++tOff0K96T5B6xC7yco9+ew==,iv:P8TydjC8vs0FdcQ5slIfOfPyKQ6l8T3UPqgROnqf6cE=,tag:kXvpKmbVds5vM3H8QE/qQA==,type:comment]
#ENC[AES256_GCM,data:nuUCksOWlvFQ7D44re5k2WCNxJ+oaS2ivktvQ6TE3ltBQyCb,iv:XQp0P+ibs3cWgSHUIYEEOiu/6rWnbpXTia7pVGgzoMQ=,tag:iOT1l0G+Mg4qORbeDKp0dw==,type:comment]
#ENC[AES256_GCM,data:ErT5/0hthgJan3ytCSOioVpEAIU69uUptBfmBeeWxfiMNWaoX9cWMfPStd0t,iv:s7eETxzR/TtGqAgvOOH7KYU5UsH4gdyqwQ55OqEctTo=,tag:0Vhhx3+S95RtDUGcZnHLaw==,type:comment]
#ENC[AES256_GCM,data:nFHp4Cx6Fu7nFT6npX5blcW5ZtDO/MBUxNBksiVq+wLEMU8XnbZLWjo=,iv:iChLFNi3hT0ciGXbupYsb8VSCXDFEDFJ0T4X7+YeDjY=,tag:lgxX4+jwACImcOJiHmk1KQ==,type:comment]
#ENC[AES256_GCM,data:oolK2OqYmUv8B8OjkzAq/CAuzjgkaLmf,iv:hAygi74q32UV5P75UZKc2E0hvmFOdM4lfvs253tFLc0=,tag:ylJmCrGIAgkco66fvyn3Tg==,type:comment]
#ENC[AES256_GCM,data:ZZiB2uquu8kI/9g0YAWz1o5KhpVFmbuw86sOrvcX2ayEnjBKpKU08Zqg6005XA==,iv:vRTEpagy6lkuOXMGhJ5EczMukhfpbZeeF+zTl+/8huc=,tag:UBa+eCwbKjIo0dHTPyb0Pg==,type:comment]
#ENC[AES256_GCM,data:qN0JI8jWsrhD6rotWzQuJ0z16ef9//28osFu5CRF,iv:fpZUSm4zIRYU4R8wO/YiDJ7PJsglEcQq4udKwFywWsc=,tag:7PlOCZGkzVmmh/qnjothhw==,type:comment]
#ENC[AES256_GCM,data:QlI4DSA3eSrcbZxVcXBolxYOTM/cU8EgpRkFyq1iwt7XG29i3dr6qe79xISzAZyMKCBBO90tb1xlYCMLThaInA==,iv:kjiKw8t+/tY8AweC2/SUaH6ii9Ex+Ip5j+LYwlSQ8eU=,tag:zScBYPArXge4DOpZNRsorQ==,type:comment]
#ENC[AES256_GCM,data:7oClvyd2B1e3dJGWF4/3sENM3m5LIw1kpN7XJqCduRd49Nu7vDgZ7wqby98TGiHjcecu7xBYbg4UZA3VNmNYQr3Mp32mvK/7BzDZYwgFrnI1Kf8B7a0/1qxjIkBQXOSWZl23RPAs+szMsU1sQuJv7uroXxZ7+q0gTjZHcqceP3QENIeRq5IGFfZ+76b2fnLVfo8+fhM9ZNZ40MTtDy3oP1EHVn++tOff0K96T5B6xC7yco9+ew==,iv:P8TydjC8vs0FdcQ5slIfOfPyKQ6l8T3UPqgROnqf6cE=,tag:kXvpKmbVds5vM3H8QE/qQA==,type:comment]
sops:
    age:
        - recipient: age15fyxdwmg5mvldtqqus87xspuws2u0cpvwheehrtvkexj4tnsqqysw6re2x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbE02eWN3WU5BUmhhU0Nr
            c1FKeWRvZXlNcy95cXBGVUd0aXFaTWVDK1h3CkFiaW1URUEvZVRmbCtXeXh5ZXZv
            MGowZkh2emF1bnNKcnJMNnFuU1FjUzAKLS0tIEs3SFBsMG5POFNtQ0tSbWFvcjVF
            YnZkRjFiTEFNWlZhc3YzTjdrdFdtR1kKi3tUPR2WKfg8ZJrMY9ZKRb7BXU9j/5MK
            Y3xiAmh8/IJlGkWr4NIHtRmvCUQNMqBYSJnAjBTu+3fRdNELqW/N7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qy04neuzwpasmvljqrcvhwnf0kz5cpyteze38c8avp0czewskasszv9pyw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbTdGQ0VMc0xoLytta0Zo
            L2t0WDd0SktXRHJXcnllejBQZzBtTi9wQ0FJCmhWTVMzeDdmVTlxbi8yRTl6d1cr
            dW5YN2RCOTcwM216eEMyN080azlMR3MKLS0tIDlUL0lpSlV5YllLQUJHZUcvUzVB
            UkJkT2lTZWFDTkJHM0lyN2RjUEczTmsKy9D6/1cKAqi0s9NPvHDPDNbiM+9WkcGL
            ujoHuDvckf1JFux/6gXnMz1qfhJj18G7kay2rd1Q8i4AvQFRNWv3vA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zh33t0mqh3mpsvclhtp6rfvlru3aa4jy6du0ud79jhn72kz9j40q5vnkat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaFo3eHMrTHRLK0M3R00x
            UFF1ZldXTlVGOUlWK2FQRDk2WVVxNFkxaURrCnpPVnB6bjVDZUx4dERUTThEUGUz
            T1ZKNG4wenVHL0VkNTlwQ3czelh3QTAKLS0tIGFJUWczSkgyVlZVbnRiWVlhMkRC
            c3BZT0k4eEc3VzJxRXdYQ25kQ1dQNVkKY0h0DHZS5q2kndRhS42MZgsszZxj8Qxo
            ub2wjOtdwzDNhpPD3aBpIImjA4qgSk/WLi/WTXd/6fNwpKRzds6TAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xvckqrat9q6lfh24ax6y65qzde6krm4a2s0uc83ursr7gas8eavswf5kpl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYkgwZWFGOHBrMjNvdnpW
            Q1p4aG5SSE84TUNINWlwZ05wc0hPUUw1YWtJCmpOTFUyR1JFbkRORmtQYjlqNWFj
            SGFXVnZ3UXFSZE5KMG9BOENlUVhuMXcKLS0tIDdnWTZBSWdXbC9TZGFRVVFieTlZ
            bERqMWpPVE1SRjJBdWpCd01JclpQQ00KGfeArXypv62XjToWOh0baa3Z6MkoQmZu
            2EkuSXjP+XRv+aE+C+FyYqaG1sWb9m6xsQiGmltali93dCu6AWiH6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T14:31:54Z"
    mac: ENC[AES256_GCM,data:yYhva6CgQf04mK4BXwYFuWN5GYEf9hSLCFCVYxtHFr3hN3HCbRoPRXqOhG/rbJ0Lhn3oXJy8/GrSm0wRZDQyUXs3CBEfmNva1DZIEcBNFh2kIKmKHArDe9n6iofuWqMd1ypBkLDZ6kEDS2MjQMQVdVkllTUO+7ScolPhAQIRUsA=,iv:AV2Z+3JU7cHcgQsik5CIXnWBHpicitF0HjEX+oPy0nM=,tag:/G+9lGugV0vSpGod4Mdfpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
