apiVersion: v2
name: albert-stack
description: A Helm chart for Albert API Stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "19.1.3"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    
  - name: qdrant
    version: "1.15.1"
    repository: https://qdrant.github.io/qdrant-helm