apiVersion: v2
name: opengatellm-stack
description: A Helm chart for OpenGateLLM Stack
type: application
version: 0.4.0
appVersion: "0.3.5post2"

dependencies:
  - name: postgresql
    version: "18.1.11"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    tags:
      - opengatellm-stack-database
  - name: redis
    version: "23.2.12"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    tags:
      - opengatellm-stack-cache
  - name: vllm-stack
    version: "0.1.8"
    repository: "https://vllm-project.github.io/production-stack"
    condition: vllm-stack.enabled
    tags:
      - opengatellm-stack-inference
  - name: eck-operator-crds
    version: "3.2.0"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
    tags:
      - opengatellm-stack-search
  - name: eck-operator
    version: "3.2.0"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
    tags:
      - opengatellm-stack-search
