apiVersion: v1
kind: ConfigMap
metadata:
  name: albert-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "albert-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: albert-api
data:
  config.yml: |
    # Albert config.yml
    {{- toYaml .Values.albertApi.config | nindent 4 }}