apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embeddings-models-pvc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "albert-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: embeddings
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}