apiVersion: v1
kind: Service
metadata:
  name: playground
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "albert-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: playground
spec:
  selector:
    app: playground
  ports:
    - port: {{ .Values.playground.service.port }}
      targetPort: {{ .Values.playground.service.targetPort }}
      name: http
  type: {{ .Values.playground.service.type }}