{{- if .Values.opengatellm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: opengatellm
  labels:
    {{- include "opengatellm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: opengatellm
spec:
  selector:
    app: opengatellm
  ports:
    - port: {{ .Values.opengatellm.service.port }}
      targetPort: {{ .Values.opengatellm.service.targetPort }}
      name: http
  type: {{ .Values.opengatellm.service.type }}
{{- end }}
