{{- if .Values.opengatellm.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: opengatellm-stack-playground
  labels:
    {{- include "opengatellm-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: playground
spec:
  selector:
    app: opengatellm-stack-playground
  ports:
    - port: {{ .Values.streamlit.service.port }}
      targetPort: {{ .Values.streamlit.service.targetPort }}
      name: http
  type: {{ .Values.streamlit.service.type }}
{{- end }}
