apiVersion: v1
kind: Secret
metadata:
  name: vllm-api-key
  namespace: {{ .Values.global.namespace | default "default" }}
  labels:
    {{- include "opengatellm-stack.labels" . | nindent 4 }}
type: Opaque
data:
  api_key: {{ .Values.vllm.api_key | b64enc | quote }}